version: '3'
services:
  webapi_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    network_mode: bridge
  mongo_db:
    image: mongo:6.0.4
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"