version: '3'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:18080"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"